# Generated by Django 2.0.5 on 2020-07-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FMLOGIN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='経度')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='緯度')),
                ('IP_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='システムIPアドレス')),
                ('NIC', models.CharField(blank=True, max_length=255, null=True, verbose_name='システムNICアドレス')),
                ('NPC', models.CharField(blank=True, max_length=255, null=True, verbose_name='ネットワークプロトコル')),
                ('SPH', models.CharField(blank=True, max_length=255, null=True, verbose_name='システムプラットホーム')),
                ('SV', models.CharField(blank=True, max_length=255, null=True, verbose_name='システムバージョン')),
                ('AV', models.CharField(blank=True, max_length=255, null=True, verbose_name='アプリケーションバージョン')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
